on: pull_request
name: PR Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Update permissions on mvnw
      run: chmod 700 mvnw
    - name: Package
      run: ./mvnw clean package --no-transfer-progress
